// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXQCLWNYNl52N3pDeuAf2xxBhnst2PWY',
    appId: '1:1090572091531:android:24895c3b4824ed92d2948e',
    messagingSenderId: '1090572091531',
    projectId: 'afrogrids',
    storageBucket: 'afrogrids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNFOVKSh6YE4KhVZDMWCaZJRYzeM_9sv0',
    appId: '1:1090572091531:ios:7cf7b08bbf298af1d2948e',
    messagingSenderId: '1090572091531',
    projectId: 'afrogrids',
    storageBucket: 'afrogrids.appspot.com',
    androidClientId: '1090572091531-6b96jtn87rabvb5gno5c1k2g6891s1sf.apps.googleusercontent.com',
    iosClientId: '1090572091531-6j5hg59h408bms22q2g4n9in0sm2b34f.apps.googleusercontent.com',
    iosBundleId: 'com.cyberjroid.afrogrids',
  );
}
